# -*- coding: utf-8 -*-

# 100 CÂU SPAM TAG RÉO TÊN BỰA & CAY CÚ
SPAM_TAG_PREFIXES = [
    "Dậy đi ông cháu ơi {tag}!",
    "Alo {tag} sủa lên xem nào?",
    "Hiện hồn về rep tin nhắn ngay {tag}!",
    "{tag} mày chết lâm sàng rồi à?",
    "Rep tin nhắn mau con lợn {tag}!",
    "{tag} ngủ gì mà như chết trôi thế?",
    "Alo {tag} có thở không đấy?",
    "{tag} đang đi ỉa hay gì mà lâu thế?",
    "Crush nhắn tin mày rep trong 1 giây, còn tao nhắn mày ngâm 3 ngày hả {tag}?",
    "{tag} trốn nợ à? Mau hiện hình!",
    "Bớ người ta thằng {tag} nó ngất rồi!",
    "{tag} ơi, mẹ mày bảo về ăn cơm kìa!",
    "Ủa {tag}, tay mày bị liệt à mà không gõ phím được?",
    "{tag} bật wifi lên mà đọc tin nhắn này!",
    "Tao réo cho đến khi nào mày rep mới thôi nhé {tag}!",
    "{tag} ơi là {tag}, làm ăn thế à?",
    "Alo tổng đài, tìm giúp tôi con chó tên {tag} với!",
    "{tag} mày đang bận đóng phim với crush à?",
    "Tag nhẹ cái cho mày giật mình chơi {tag} 😏",
    "{tag} sủi đi đâu rồi con?",
    "Này {tag}, sống có tâm tí đi xem nào!",
    "{tag} ơi rep đi tao cho kẹo mút nè 🍭",
    "Một chấm là say đắm, hai chấm là {tag} bị đấm 🥊",
    "{tag} đang xem xiếc hay sao mà bận thế?",
    "Alo {tag}, server đang nhớ mày lắm đấy!",
    "{tag} mày có coi tao ra gì không?",
    "Đừng để tao phải đến tận nhà lôi đầu mày dậy nhé {tag}!",
    "{tag} ơi, cô giáo gọi lên bảng trả bài kìa!",
    "Ting ting! Bạn có 1 thông báo bị chửi từ tao nè {tag}!",
    "{tag} ngáo ngơ vừa thôi, rep mau!",
    "Đang làm gì đấy {tag}, thủ dâm tư tưởng à?",
    "{tag} mày mà không rep là tao hack nick mày đấy!",
    "Alo {tag}, xe cấp cứu đang đợi mày dưới nhà kìa 🚑",
    "{tag} ơi dậy đi học bài đi con!",
    "Ê {tag}, người ta có người yêu rồi, rep tao đi đừng lụy nữa!",
    "{tag} bớt xem story crush lại và rep tin nhắn tao đi!",
    "Tag lần thứ n cho thằng {tag} sáng mắt ra!",
    "{tag} nghe rõ trả lời, over!",
    "Alo {tag}, công an phường tìm mày kìa!",
    "{tag} ơi, mày là người hay là tượng sáp thế?",
    "Chắc {tag} đang bận làm chú hề rồi 🤡",
    "{tag} không rep là mặc định nhận nợ 500k nhé!",
    "Alo {tag}, thức tỉnh đi hỡi con chiên ngoan đạo!",
    "{tag} ơi, đừng để tao phát điên lên nhé!",
    "Tao đếm từ 1 đến 3 mày không rep là tới công chuyện với tao đấy {tag}!",
    "{tag} có người tìm mày ở cổng trường kìa!",
    "Ê {tag}, mày thở ra xem còn sống không?",
    "{tag} ơi rep đi tao bao trà sữa 🧋 (nói phét đấy)!",
    "Alo {tag}, mày đang ở sao Hỏa hay sao Thổ thế?",
    "{tag} bớt lươn khươn đi nha con!",
    "Réo cho mày rung bần bật cái điện thoại luôn {tag} 📳",
    "{tag} ơi, mày đang bận đếm tiền à?",
    "Nhìn mặt mày là thấy ghét rồi {tag}, rep mau!",
    "{tag} ơi dậy đi, gà gáy 3 cữ rồi!",
    "Alo {tag}, mày đang trốn ai đấy?",
    "{tag} không rep là làm con cún 🐶 gâu gâu!",
    "{tag} ơi rep tao đi mà, tao xin mày đấy (đùa đấy đấm chết giờ)!",
    "Có ai thấy thằng {tag} đâu không, nó mất tích rồi!",
    "{tag} ơi, mày bị người ngoài hành tinh bắt cóc rồi à? 👽",
    "Alo {tag}, bật thông báo Discord lên con lợn!",
    "{tag} ơi, hôm nay mày ăn bún mắng cháo chửi chưa?",
    "Tag phát nữa cho mày nhớ mặt tao {tag}!",
    "{tag} ơi, mày định biến mất vĩnh viễn à?",
    "Ê {tag}, rảnh rỗi sinh nông nổi à mà ngâm tin nhắn?",
    "{tag} mà không rep là tối nay mơ thấy ác mộng nhé!",
    "Alo {tag}, đừng để tao phải dùng bùa ngải!",
    "{tag} ơi, mày vừa rơi xuống hố phân à?",
    "Réo tên con nợ tâm linh {tag}!",
    "{tag} ơi, crush mày bảo ghét mày kìa!",
    "Alo {tag}, mày vừa bị sét đánh à mà im re?",
    "{tag} sủa một tiếng cho tao yên tâm nào 🐕",
    "Tag {tag} để nhắc nhở mày vẫn chỉ là lốp dự phòng 🛞",
    "{tag} ơi, mày có biết tao đang bực lắm không?",
    "Alo {tag}, điện thoại mày để làm cảnh à?",
    "{tag} không rep là tao spam cho cháy máy!",
    "{tag} ơi, tiền net hết rồi kìa nạp đi!",
    "Ê {tag}, mày đang bận khóc vì tình yêu à?",
    "{tag} ơi, dậy rửa mặt cho tỉnh táo đi con!",
    "Alo {tag}, có tin mật cực hot nè rep mau!",
    "{tag} ơi, mày vừa bị mất trí nhớ à?",
    "Tag {tag} cái nhẹ cho đời thêm vui!",
    "{tag} ơi, mày là thánh ngâm thơ hay thánh ngâm tin nhắn?",
    "Alo {tag}, có người bảo mày nhìn giống khỉ đột kìa 🦍",
    "{tag} ơi, rep đi không tao méo thèm chơi với mày nữa!",
    "Ê {tag}, mày có biết giờ là mấy giờ rồi không?",
    "{tag} ơi, bật 4G lên đi nhà nghèo quá à?",
    "Alo {tag}, tao đang đứng trước cửa phòng mày nè!",
    "{tag} không rep là mai ăn trứng vịt lộn bị ung nhé!",
    "{tag} ơi, dậy đi quẩy game thôi con gà!",
    "Ê {tag}, mày đang bận ngắm ảnh crush à?",
    "Alo {tag}, đừng giả vờ bận rộn nữa tao biết thừa mày đang lướt TikTok!",
    "{tag} ơi, rep tao ngay trước khi quá muộn!",
    "Tag cho {tag} tỉnh cả ngủ lẫn ngáo!",
    "{tag} ơi, mày là người hay là bóng ma thế? 👻",
    "Alo {tag}, rep mau không tao report nick mày bay màu!",
    "{tag} ơi, mẹ mày gọi về gấp kìa!",
    "Ê {tag}, làm người ai làm thế, rep đi chứ!",
    "{tag} ơi, mày vừa uống nhầm thuốc ngủ à?",
    "Alo {tag}, tiếng gọi nơi hoang dã tìm mày kìa!",
    "Chốt hạ phát cuối: {tag} MÀY CÓ REP KHÔNG THÌ BẢO? 💣"
]

# 100 CÂU CHÀO MỪNG THÀNH VIÊN MỚI VÀO SERVER (JOIN)
JOIN_MESSAGES = [
    "Chào mừng con mồi mới {tag} đã gia nhập chuồng hề. 🤡",
    "Ơ kìa {tag} lạc vào chuồng thú rồi à? Chào mừng nhé! 🎪",
    "Thêm một nạn nhân mới... à nhầm, thêm một thành viên mới {tag}! Chào mừng! 🎉",
    "Hú hú {tag} ơi! Vào chuồng nhớ chào các đại ca nhé! 🐒",
    "Cả lò chú ý: {tag} đã bước chân vào hang quỷ! 🚨",
    "Vỗ tay nồng nhiệt chào đón {tag} - người dũng cảm bước vào động hề! 👏",
    "{tag} vừa nhảy dù vào server, hy vọng tiếp đất an toàn bằng mặt! 🪂",
    "Chào mừng {tag}! Mang theo tiền đóng quỹ lớp chưa đấy? 💸",
    "Một sinh linh bé bỏng mang tên {tag} vừa sa vào lưới tình của Server. 🕸️",
    "{tag} đã xuất hiện! Hãy chuẩn bị tâm lý để bị troll nhé! 😈",
    "Chào mừng {tag}! Đề nghị xuất trình giấy khám sức khỏe tâm thần trước khi chat! 🩺",
    "Ơ {tag} ơi, vào đây là không có đường lui đâu nhé! 🚪🔒",
    "Loa loa loa! {tag} vừa mò mặt vào server, anh em đâu ra tiếp đón! 📢",
    "{tag} đã gia nhập hội những người phát cuồng vì cuộc sống. ✨",
    "Chào mừng {tag}! Ở đây chúng tôi không có gì ngoài sự hài hước và nghèo khó. 🍜",
    "Ting ting! Máy chủ vừa thu nạp thêm một chú khỉ con {tag}! 🐵",
    "{tag} vừa vào server! Mau quỳ xuống nhận lãnh đạo đi nào! 👑",
    "Chào mừng {tag}! Vào nhớ đọc nội quy, không là ăn gậy của Admin đấy! 📜",
    "Hé lô {tag}! Hy vọng bạn trụ được ở đây quá 3 ngày mà không phát điên. 🤪",
    "{tag} đã vào! Bật mic lên và sủa một bài chào sân xem nào! 🎙️",
    "Chào mừng siêu sao {tag} đã hạ cánh xuống trái đất! 🛸",
    "{tag} ơi, bạn vừa bước vào nơi quy tụ những thành phần bất hảo nhất Discord. 🕶️",
    "Cửa mở rồi, {tag} bước vào đi, chúng tao đang đợi mày đấy! 🚪",
    "Chào mừng {tag}! Vào đây làm lốp dự phòng hay làm chú hề thế? 🤡🛞",
    "{tag} đã tham gia! Hãy mang theo trà sữa để hối lộ anh em nhé! 🧋",
    "Chúc mừng {tag} đã tìm thấy ngôi nhà thứ 2... à không, trại tị nạn thứ 2! 🏕️",
    "{tag} vừa xuất hiện như một vị thần, nhưng thần đèn hay thần đần thì chưa biết. 🧞",
    "Chào mừng {tag}! Ở đây có wifi miễn phí và bánh mì bơ tỏi tâm linh. 🍞",
    "{tag} ơi, vào nhớ bật cam, bật mic và tắt não đi nhé! 🧠❌",
    "Cảnh báo: {tag} vừa xâm nhập vào vùng phủ sóng của chuồng hề! ⚠️",
    "Chào mừng {tag}! Mau chọn cho mình một vai trò để không bị coi là người vô gia cư. 🏷️",
    "{tag} đã gia nhập! Chúc bạn có những phút giây tiền đình vui vẻ! 😵",
    "Hú hồn chim én! {tag} đã mò được đường vào đây rồi à? 🐦",
    "Chào mừng {tag}! Hãy để lại lòng tự trọng ở cửa trước khi bước vào nhé. 🚪",
    "{tag} vừa vào server! Ai cho mày vào đấy hả con lợn? 🐷 (đùa đấy chào mừng nhé!)",
    "Chào mừng đồng chí {tag} đã đầu hàng vô điều kiện trước Server! 🏳️",
    "{tag} đã vào! Chuẩn bị tinh thần ăn gạch đá nặc danh từ /nemda nhé! 🧱",
    "Chào mừng {tag}! Nơi đây ấm áp tình đồng chí, thơm nồng mùi cà khịa. ☕",
    "{tag} vừa đến! Đề nghị tất cả đứng nghiêm chào cờ! 🚩",
    "Chào mừng {tag}! Nhớ kiểm tra độ lốp bằng lệnh /checklop ngay nhé! 🛞",
    "{tag} đã vào! Hãy cùng chúng tôi xây dựng một đế chế tấu hài đỉnh cao. 🏰",
    "Chào mừng {tag}! Vào đây vui là chính, nợ tiền không trả là mười. 💸",
    "{tag} ơi, bạn đã sẵn sàng trở thành Joker tiếp theo chưa? 🃏",
    "Chào mừng {tag}! Người mang lại ánh sáng le lói cho cái server u tối này. 💡",
    "{tag} vừa đặt chân vào server! Một tràng pháo tay cho sự can đảm của bạn! 🎆",
    "Chào mừng {tag}! Nơi đây không có người bình thường, chỉ có người bất thường và {tag}. 🤪",
    "{tag} đã đến! Hãy chuẩn bị hầu bao để đóng các loại thuế vô lý của Admin. 💰",
    "Chào mừng {tag}! Chúc bạn sớm hòa nhập với bầy đàn hoang dã này. 🦓",
    "{tag} vừa vào! Bật loa to lên để nghe chị Google đọc lệnh /noi nhé! 🔊",
    "Chào mừng {tag}! Một bông hoa tươi thắm vừa cắm bãi phân trâu mang tên Server. 🌸💩",
    "Chào {tag}! Bạn là thành viên thứ n+1 bị dắt mũi vào đây. 🐮",
    "{tag} đã vào! Đừng hỏi server có thể làm gì cho bạn, hãy hỏi bạn có tiền bao net không! 💻",
    "Chào mừng {tag}! Nơi tụ tập của những bàn tay vàng trong làng bốc phét. 🏆",
    "{tag} vừa xuất hiện! Hãy giữ chặt ví tiền và người yêu của bạn! 👛",
    "Chào mừng {tag}! Vào đây rồi thì đừng hòng thoát ra được nhé con mồi! 🕸️",
    "{tag} đã đến! Mang theo nụ cười và để lại nỗi buồn ngoài cổng. 😊",
    "Chào mừng {tag}! Hãy cùng nhau tạo nên những drama chấn động địa cầu. 🎭",
    "{tag} vừa vào! Xin mời thí sinh tiếp theo bước vào vòng thi tấu hài! 🎤",
    "Chào mừng {tag}! Đừng tin lời bất kỳ ai trong này, kể cả con Bot! 🤖",
    "{tag} đã gia nhập! Chúc bạn không bị sốc văn hóa trước độ bựa của server. 🌊",
    "Chào mừng {tag}! Hãy gửi 1 tấm ảnh dìm hàng để làm thủ tục nhập tịch nhé! 📸",
    "{tag} vừa vào! Một gương mặt mới toanh cho anh em tha hồ troll! 🎯",
    "Chào mừng {tag}! Nơi đây chữa lành mọi vết thương... bằng cách tạo thêm vết thương mới. 🩹",
    "{tag} đã đến! Hãy tôn trọng Admin nếu không muốn bay màu trong 1 nốt nhạc! ⚡",
    "Chào mừng {tag}! Bạn có 24h để làm quen trước khi bị đem ra làm vật tế thần. 🗿",
    "{tag} vừa vào! Hãy chuẩn bị tinh thần cày cấp với lệnh /rank nhé! 📈",
    "Chào mừng {tag}! Người mang lại niềm hy vọng mong manh cho Server. 🌟",
    "{tag} đã xuất hiện! Ai đó mau mang kiệu rước đại ca vào nào! 🏮",
    "Chào mừng {tag}! Nơi sinh ra những huyền thoại và chôn vùi những ước mơ. 🌌",
    "{tag} vừa vào server! Hãy sẵn sàng cho những đêm thức trắng cày game! 🎮",
    "Chào mừng {tag}! Vào đây là anh em một nhà, có phúc cùng hưởng có họa tự chịu! 🤝",
    "{tag} đã đến! Hãy cùng chúng tôi quậy tung nóc nhà Discord! 🏠💥",
    "Chào mừng {tag}! Chúc bạn có trải nghiệm tuyệt vời cùng lũ hề chúng tôi. 🎈",
    "{tag} vừa vào! Mau vào phòng voice làm quen các anh lớn đi nào! 🎙️",
    "Chào mừng {tag}! Người sở hữu nhan sắc nghiêng nước nghiêng thùng. 🪣",
    "{tag} đã gia nhập đại gia đình! Cấm sủi Voice nhé bạn hiền! 🚫",
    "Chào mừng {tag}! Đề nghị không manh động và làm theo hướng dẫn của quản trị viên. 👮",
    "{tag} vừa vào! Thêm một chân chạy vặt cho lớp rồi! 🏃‍♂️",
    "Chào mừng {tag}! Hãy cùng nhau viết nên những trang sử hào hùng đầy drama. 📖",
    "{tag} đã đến! Server này từ nay chính thức có thêm một thành viên ưu tú (tự phong). 🎖️",
    "Chào mừng {tag}! Hy vọng bạn không phải là gián điệp của lớp bên cạnh cài vào. 🕵️",
    "{tag} vừa vào! Mau giới thiệu tên tuổi, số đo 3 vòng và số tài khoản ngân hàng nào! 💳",
    "Chào mừng {tag}! Nơi bạn có thể bộc lộ bản chất thật mà không sợ bị phán xét. 🎭",
    "{tag} đã đến! Hãy chuẩn bị cho những trận cười ra nước mắt. 😂",
    "Chào mừng {tag}! Vào đây rồi thì xác định mất ăn mất ngủ vì vui nhé! 🥳",
    "{tag} vừa vào server! Xin đừng bỏ trốn quá sớm! 🏃‍♀️",
    "Chào mừng {tag}! Người mang theo năng lượng tích cực (hoặc tiêu cực) cho anh em. ⚡",
    "{tag} đã xuất hiện! Hãy cùng nhau leo rank và quậy phá tưng bừng nào! 🚀",
    "Chào mừng {tag}! Một nhân tố bí ẩn vừa gia nhập đội hình tấu hài. 🧩",
    "{tag} vừa vào! Hãy sẵn sàng bấm nút nhận role nhé! 🏷️",
    "Chào mừng {tag}! Ở đây chúng tôi coi trọng tình bạn hơn tiền bạc... nhưng tiền bạc vẫn hơn. 💵",
    "{tag} đã đến! Mau chào các đại ca đi không bị ăn đấm đấy! 👊",
    "Chào mừng {tag}! Chúc bạn sớm tìm được một nửa lốp xe của đời mình tại đây. 🛞❤️",
    "{tag} vừa vào server! Cả lớp đứng dậy vỗ tay 1 phút chào mừng! 👏⏳",
    "Chào mừng {tag}! Nơi biến những điều không thể thành trò hề thế kỷ. 🎪",
    "{tag} đã đến! Hãy cùng nhau quẩy tung nóc voice đêm nay! 🎧",
    "Chào mừng {tag}! Người bạn mới với nụ cười tỏa nắng (hoặc tỏa mùi). ☀️",
    "{tag} vừa vào! Chúc bạn may mắn sống sót qua mùa trăng này! 🌕",
    "Chào mừng {tag}! Hãy tận hưởng những giây phút bất ổn nhất cuộc đời bạn tại đây! 🎢",
    "Chào mừng {tag} đã chính thức bước vào ngôi nhà chung của những thiên tài bất hảo! 🏠🎉"
]

# 100 CÂU TIỄN THÀNH VIÊN RỜI SERVER (LEAVE)
LEAVE_MESSAGES = [
    "Tiễn vong **{name}**, không chịu nổi nhiệt đã bấm nút biến. 💨",
    "**{name}** đã sủi rồi nhé cả nhà, F trong chat. ⚰️",
    "Một con chim đã rời đàn... **{name}** bay đi không một lời từ biệt. 🕊️",
    "Tạm biệt **{name}**, kiếp sau đừng sủi nữa nhé! 🪦",
    "**{name}** đã chọn con đường giải thoát khỏi chuồng hề. 🚪",
    "Bay màu rồi! **{name}** đã bấm nút biến mất khỏi cuộc đời chúng ta. 💨",
    "**{name}** ra đi thanh thản, gia đình xin chân thành cảm ơn. 🙏",
    "Một đồng chí đã hy sinh... **{name}** rời bỏ chiến trường trong lặng câm. 🥀",
    "**{name}** đã cúp đuôi chạy trốn khỏi thực tại tàn khốc này. 🏃",
    "Gió đưa cành trúc la đà, **{name}** đã bấm nút sủi rồi nha cả nhà. 🎋",
    "**{name}** không chịu nổi độ bựa của server nên đã tẩu thoát thành công. 🏃‍♂️💨",
    "Vĩnh biệt cụ **{name}**, người ra đi đầu không ngoảnh lại. 🍂",
    "Một tài năng trẻ mang tên **{name}** đã từ bỏ ước mơ trở thành Joker. 🤡",
    "**{name}** đã rời server, quỹ lớp từ nay mất đi một con nợ tiềm năng. 💸",
    "Tiễn biệt **{name}** về với thế giới người bình thường. 🌍",
    "**{name}** đã biến mất nhanh hơn cả cách crush từ chối lời tỏ tình. 💨💔",
    "F để tưởng niệm sự ra đi đột ngột của **{name}**. 🕯️",
    "**{name}** đã sủi! Mong bạn tìm được server nào đỡ ngáo ngơ hơn server này. 🛸",
    "Cửa mở toang tiễn **{name}** lên đường bình an vô sự! 🚪✨",
    "**{name}** đã rời khỏi cuộc chơi vì không chịu nổi áp lực từ dư luận. 🗣️",
    "Tạm biệt **{name}**, người từng hứa ở lại trọn đời nhưng sủi sau 3 ngày. 💔",
    "**{name}** đã bay màu khỏi Trái Đất, hẹn gặp lại ở kiếp khác! 🚀",
    "Một ghế trống trong chuồng thú... **{name}** đã trèo tường vượt ngục. 🧗",
    "**{name}** ra đi để lại bao tiếc thương và một đống nợ chưa trả. 🧾",
    "Tiễn vong **{name}**, mong bạn sang bên kia sống tốt hơn bên này. 💐",
    "**{name}** đã bấm nút out server! Đồ hèn nhát không dám đối mặt sự thật! 😤",
    "Một giọt nước mắt rơi xuống tiễn đưa linh hồn **{name}** rời bến. 💧",
    "**{name}** đã đi xa, rất xa... xa khỏi tầm mắt của Admin. 🔭",
    "Tạm biệt **{name}**, cảm ơn vì đã ghé qua tấu hài vài hôm rồi sủi. 🎭",
    "**{name}** đã rút lui trong danh dự (hoặc nhục nhã). 🏳️",
    "Người đi một nửa hồn tôi mất, một nửa hồn tôi bấm nút tiễn **{name}**. 📜",
    "**{name}** đã chọn cuộc sống yên bình, từ bỏ anh em bất hảo. 🧘",
    "Tiễn đưa **{name}**, một nén hương lòng gửi đến phương xa. 🪔",
    "**{name}** đã sủi bọt tăm, không để lại dù chỉ một dấu vết. 🫧",
    "Một thành viên đã rời đi... **{name}** chúc bạn may mắn lần sau! 🎲",
    "**{name}** đã out server! Chắc là bận đi lấy vợ/chồng rồi. 💍",
    "Tiễn bạn **{name}** lên đường, nước mắt tuôn rơi trên bàn phím. ⌨️😭",
    "**{name}** đã trốn thoát khỏi trại tâm thần thành công rực rỡ! 🏥🏃",
    "Vĩnh biệt **{name}**, từ nay không còn ai gánh tạ cho chúng ta nữa. 🏋️",
    "**{name}** đã bấm nút biến! Mong bạn không hối hận vì quyết định này! ⏳",
    "Một cánh én nhỏ chẳng làm nên mùa xuân, **{name}** bay đi mùa đông lại về. ❄️",
    "**{name}** đã rời đàn! Đề nghị anh em không khóc lóc quá nhiều. 🧻",
    "Tiễn vong **{name}**, người bạn từng thân thiết nay hóa người dưng. 🚶‍♂️",
    "**{name}** đã biến mất như chưa từng tồn tại trên thế gian này. 🌫️",
    "Thế là hết, **{name}** đã dứt áo ra đi không một lời chào tạm biệt. 🧥",
    "**{name}** đã chọn cách bấm nút đỏ nguy hiểm và biến mất. 🔴",
    "Tạm biệt **{name}**, chúc bạn sang server khác không bị ăn đấm! 🥊",
    "**{name}** đã sủi! Cả server đồng thanh hô: TIỄN VONG! 🗣️⚡",
    "Một khoảng trống mênh mông để lại sau sự ra đi của **{name}**. 🕳️",
    "**{name}** đã rời cuộc họp vì hết tiền 4G. 📶❌",
    "Tiễn bạn **{name}**, mong bạn sớm tìm được chân lý cuộc đời. ☀️",
    "**{name}** đã bay đi theo tiếng gọi nơi hoang dã. 🐺",
    "Hết duyên hết nợ, **{name}** chính thức xóa sổ khỏi Server! ✂️",
    "**{name}** đã rút lui vào bóng tối, trở thành huyền thoại đã khuất. 🌑",
    "Tạm biệt **{name}**, người ra đi để lại một bầu trời thương nhớ (và nợ). 💭",
    "**{name}** đã rời server! Đỡ chật đất, đỡ tốn băng thông! 🧹",
    "Tiễn đưa **{name}**, chúc bạn tìm được bến đỗ bình yên hơn cái ổ quỷ này. ⚓",
    "**{name}** đã out! Chắc là bị mẹ gõ đầu bắt đi học bài rồi. 📚",
    "Một người bạn đã rời xa... **{name}** hẹn kiếp sau ta lại làm anh em! 🤝",
    "**{name}** đã bấm nút biến hình và tan biến vào hư vô. 🌌",
    "Vĩnh biệt **{name}**, người hùng thầm lặng của những trận thua chuỗi. 📉",
    "**{name}** đã rời khỏi chuồng! Cổng trại đóng lại vĩnh viễn! 🚪🔒",
    "Tiễn vong **{name}**, mong bạn không gặp ác mộng về con Bot này. 🤖",
    "**{name}** đã sủi như một cơn gió mùa thu se lạnh. 🍂",
    "Tạm biệt **{name}**, chúc bạn sớm cai nghiện Discord thành công! 💊",
    "**{name}** đã rời bỏ chúng ta... F to Pay Respect. 🫡",
    "Một ngôi sao vừa rụng khỏi bầu trời server, đó là **{name}**. 🌠",
    "**{name}** đã out server! Đừng quay lại nữa nhé đồ phản bội! 🐍",
    "Tiễn đưa **{name}**, người bạn dũng cảm nhất từng chịu đựng server này. 🛡️",
    "**{name}** đã bay màu không dấu vết! Cảnh sát đang vào cuộc điều tra! 🚔",
    "Tạm biệt **{name}**, chúc bạn luôn vui tươi dù ở bất kỳ xó xỉnh nào! 🌻",
    "**{name}** đã rời đi! Server bớt đi một đứa ăn hại, thêm một phần bình yên. 🧘‍♂️",
    "Tiễn vong **{name}**, hãy sống thật tốt ở thế giới ngoài kia nhé! 🌈",
    "**{name}** đã sủi! Hy vọng bạn không mang bí mật server đi bán đứng. 🕵️‍♂️",
    "Một nén nhang cho sự ra đi lặng lẽ của **{name}**. 🕯️",
    "**{name}** đã bấm nút hủy diệt tư cách thành viên. 💣",
    "Tạm biệt **{name}**, người từng làm rạng danh dòng họ hề chúa. 🎪",
    "**{name}** đã out! Bỏ lại anh em bơ vơ giữa dòng đời xô đẩy. 🌊",
    "Tiễn đưa **{name}**, tiếng kèn đưa tiễn vang vọng khắp server. 🎺",
    "**{name}** đã rời khỏi trận chiến! Thất bại ê chề! 📉",
    "Tạm biệt **{name}**, người mang theo bao hoài bão nhưng sủi sớm. 🎈",
    "**{name}** đã biến mất! Chắc là bị bắt đi nghĩa vụ quân sự rồi. 🪖",
    "Tiễn vong **{name}**, hãy an nghỉ nơi chín suối... à nhầm, server khác! 🕊️",
    "**{name}** đã out! Một tràng pháo tay tiễn biệt người anh em! 👏",
    "Tạm biệt **{name}**, chúc bạn sớm tìm được crush mới chịu rep tin nhắn. 💌",
    "**{name}** đã sủi! Server từ nay vắng bóng một cây hài cộm cán. 🎭",
    "Một cánh cửa khép lại, **{name}** bước ra và không bao giờ trở lại. 🚪🚶",
    "Tiễn đưa **{name}**, người bạn đồng hành từng cùng nhau gánh chịu bao cay đắng. 🍵",
    "**{name}** đã rời đi trong sự ngỡ ngàng của toàn thể quần chúng nhân dân. 😲",
    "Tạm biệt **{name}**, chúc bạn luôn may mắn và không bị ai đòi nợ nữa! 💸❌",
    "**{name}** đã out! Hãy nhớ rằng server này từng coi bạn là một phần gia đình. ❤️",
    "Tiễn vong **{name}**, bay đi cánh chim không mỏi! 🦅",
    "**{name}** đã sủi rồi! Mong bạn sớm tìm được ánh sáng chân lý! 💡",
    "Tạm biệt **{name}**, kết thúc một cuộc tình đầy ngang trái. 💔",
    "**{name}** đã rời khỏi phòng chat! Một phút mặc niệm bắt đầu! ⏱️",
    "Tiễn đưa **{name}**, mong bạn kiếp sau đầu thai vào server xịn sò hơn. 🏰",
    "**{name}** đã out server! Cảm ơn vì tất cả những trận cười bạn mang lại! 😂",
    "Tạm biệt **{name}**, người hùng sa cơ lỡ bước! 🧗‍♂️",
    "**{name}** đã biến mất như một giấc mơ trưa hè oi ả. ☀️",
    "Chính thức tiễn vong **{name}** rời khỏi Server! Hẹn không bao giờ gặp lại! 💨🚪👋"
]

# 100 CÂU THÔNG BÁO VÀO PHÒNG VOICE (VC JOIN)
VC_JOIN_MESSAGES = [
    "Chào mừng đại ca {mention} đã mò mặt vào chuồng. 🎙️",
    "{mention} đã xuất hiện! Huyền thoại trở lại! 👑",
    "Ơ kìa {mention} hôm nay cũng rảnh à? 😏",
    "Cả lò chú ý: {mention} đã cắm đầu vào voice! 🚨",
    "{mention} lên mic đi, câm hay sao mà im re? 🎤",
    "Hú hồn! {mention} vừa chui vào phòng làm giật cả mình! 👻",
    "{mention} đã vào! Mau bật mic lên hót một bài nghe chơi! 🐦",
    "Đại gia {mention} vừa ghé thăm phòng thoại! Anh em xin tí lộc nào! 🧧",
    "{mention} đã kết nối! Đề nghị không thở mạnh vào mic nhé! 🫁",
    "Ơ kìa, ai mở cửa cho {mention} vào thế này? 🚪",
    "Chào mừng {mention}! Phòng thoại từ nay đã bớt yên bình rồi. 🔊",
    "{mention} vừa vào! Chuẩn bị tinh thần nghe nó gáy đi anh em! 🐔",
    "Alo {mention}, mang theo nước uống chưa mà vào nói nhiều thế? 🥤",
    "{mention} đã vào phòng thoại! Đề nghị anh em giữ trật tự cho nó xàm xí! 🤫",
    "Chào mừng {mention}! Vào đây để giao lưu hay để câm mic nghe trộm thế? 🕵️",
    "{mention} vừa xuất hiện! Huyền thoại gánh tạ của server đây rồi! 🏋️",
    "{mention} đã vào! Mau bật nhạc lên quẩy tưng bừng nào! 🎵",
    "Ơ {mention} chưa đi ngủ à mà vào đây giờ này? 🛌",
    "Chào mừng {mention}! Giọng ca vàng trong làng bóp mic đã xuất hiện! 🎶",
    "{mention} đã cắm tai nghe vào phòng! Bắt đầu buổi đàm đạo thế kỷ! 🎧",
    "{mention} vừa vào! Có tin gì hot kể nghe coi nào! ☕",
    "Chào mừng {mention}! Phòng này có máy lạnh, cứ tự nhiên như ở nhà nhé! ❄️",
    "{mention} đã vào voice! Đề nghị tắt quạt chĩa thẳng vào mic! 🌪️",
    "Hú le {mention}! Vào đây để nghe chị Google tấu hài đúng không? 🤡",
    "{mention} vừa nhảy vào phòng thoại! Tiếp đất bằng mông! 🍑",
    "Chào mừng {mention}! Đứa nào nợ tiền {mention} mau trốn đi kìa! 💸",
    "{mention} đã vào! Cả phòng đứng dậy chào cờ! 🚩",
    "{mention} vừa xuất hiện như một cơn gió mát lành giữa trưa hè. 🍃",
    "Alo {mention}! Nói gì đi chứ đừng có ngồi thở dốc như thế! 😮‍💨",
    "Chào mừng {mention}! Chuyên gia tâm lý học đường đã có mặt! 🧠",
    "{mention} đã vào! Chuẩn bị mở mic karaoke thâu đêm suốt sáng! 🎙️✨",
    "{mention} vừa vào phòng! Hy vọng không phải vào để rên rỉ giờ thi! 📝",
    "Chào mừng {mention}! Người mang lại tiếng cười (và sự ức chế) cho anh em. 😂",
    "{mention} đã kết nối thành công! Tín hiệu cực kỳ ổn định! 📶",
    "Ơ kìa {mention}, crush bỏ hay sao mà vào voice tìm người tâm sự? 💔",
    "Chào mừng {mention}! Cả phòng đang đợi mày vào để chửi đấy! 🤬 (đùa thôi)",
    "{mention} vừa vào! Bật mic lên gáy xem hôm nay rank gì rồi? 🏆",
    "Hú hú {mention}! Vào quẩy game thôi chứ ngồi đấy làm gì! 🎮",
    "Chào mừng {mention}! Nơi đây lắng nghe mọi nỗi niềm thầm kín của bạn. 👂",
    "{mention} đã vào! Đề nghị không ăn uống nhai nhồm nhoàm trong mic! 🍜",
    "{mention} vừa xuất hiện! Ai đó mau bưng trà rót nước cho đại ca! 🍵",
    "Chào mừng {mention}! Người sở hữu chất giọng quyến rũ chết người. 💋",
    "{mention} đã vào phòng thoại! Không khí bỗng trở nên căng thẳng! ⚡",
    "Ơ {mention}, hôm nay tắm rửa sạch sẽ chưa mà dám vào voice? 🚿",
    "Chào mừng {mention}! Cây hài cộm cán của lớp đã online! 🎪",
    "{mention} vừa vào! Mau dùng lệnh /noi để chị Google đọc hộ nào! 🗣️",
    "{mention} đã cắm mặt vào phòng thoại! Bắt đầu ca trực đêm! 🌙",
    "Chào mừng {mention}! Người duy nhất có thể chịu đựng được độ ngáo của phòng này. 🤪",
    "{mention} vừa vào! Mau khai báo lý do vào muộn! ⏰",
    "Alo {mention}! Vào là phải nói, cấm được bật chế độ tàng hình! 🥷",
    "Chào mừng {mention}! Một bông hoa rực rỡ vừa nở trong phòng voice! 🌺",
    "{mention} đã vào! Chuẩn bị nhận bão tag từ anh em! 🌪️",
    "{mention} vừa xuất hiện! Hãy cùng nhau nâng ly chúc mừng! 🍻",
    "Chào mừng {mention}! Nơi tụ họp của những con cú đêm chính hiệu! 🦉",
    "{mention} đã vào phòng! Đề nghị chỉnh lại âm lượng mic cho vừa tai! 🎚️",
    "Ơ kìa {mention}! Hôm nay rảnh rỗi thế, không phải đi học à? 🎒",
    "Chào mừng {mention}! Nhân tố gánh team (hoặc bóp team) đã xuất hiện! 🎯",
    "{mention} vừa vào! Mau kể chuyện ma cho cả phòng nghe nào! 👻",
    "{mention} đã kết nối! Chúc bạn có một buổi tối đầy ắp tiếng cười! 🌟",
    "Chào mừng {mention}! Người bạn đáng tin cậy của mọi cuộc vui! 🤝",
    "{mention} vừa vào phòng thoại! Hãy chuẩn bị cho những pha tấu hài đỉnh cao! 🚀",
    "Alo {mention}! Vào nhớ giữ gìn trật tự chung nhé con! 🤫",
    "Chào mừng {mention}! Tiếng bước chân của đại ca làm rung chuyển cả Discord! 👣",
    "{mention} đã vào! Mau vào kênh chat gõ lệnh /checklop xem độ simp nào! 🛞",
    "{mention} vừa xuất hiện! Ánh hào quang chói lóa cả phòng voice! ✨",
    "Chào mừng {mention}! Đừng ngại ngần, cứ mở mic tâm sự đi bạn hiền! 💬",
    "{mention} đã vào! Chúc bạn không bị điếc tai vì tiếng hét của anh em! 🙉",
    "{mention} vừa chui vào phòng thoại! Bắt đầu chương trình trò chuyện đêm khuya! 📻",
    "Chào mừng {mention}! Khách quý ghé thăm, phòng thoại rực rỡ hẳn lên! 🏮",
    "{mention} đã kết nối! Đề nghị anh em nhiệt liệt chào đón bằng một tràng vỗ tay! 👏",
    "Ơ {mention}, lại trốn người yêu vào đây chơi game đúng không? 🎮😏",
    "Chào mừng {mention}! Người sở hữu mic rè nhất vũ trụ đã vào! 📻💥",
    "{mention} vừa vào! Mau chia sẻ màn hình xem đang làm gì bậy bạ nào! 🖥️",
    "{mention} đã vào phòng! Không say không về nhé anh em! 🍾",
    "Chào mừng {mention}! Cảm ơn bạn đã tiếp thêm sinh khí cho cái phòng này! 🔋",
    "{mention} vừa xuất hiện! Hãy cùng nhau tạo nên những khoảnh khắc đáng nhớ! 📸",
    "Alo {mention}! Vào đây rồi thì đừng hòng sủi sớm nhé! 🔒",
    "Chào mừng {mention}! Chúc bạn có một trải nghiệm voice thật mượt mà! 🌊",
    "{mention} đã vào! Mau bật mic chào cả lò chuồng hề đi nào! 🤡",
    "{mention} vừa vào phòng thoại! Hãy sẵn sàng cho những trận battle căng thẳng! 🥊",
    "Chào mừng {mention}! Người mang lại niềm vui bất tận cho mọi người! 🎈",
    "{mention} đã kết nối! Hãy cùng nhau tâm sự chuyện đời chuyện người! ☕",
    "{mention} vừa vào! Đề nghị không khóc lóc vì điểm thi kém nhé! 📊",
    "Chào mừng {mention}! Một thành viên gương mẫu (hoặc bất hảo) vừa tham gia! 🎖️",
    "{mention} đã vào phòng thoại! Bật mic lên và nói lời yêu thương nào! ❤️",
    "{mention} vừa xuất hiện! Hãy giữ vững phong độ gáy to như mọi khi nhé! 📣",
    "Chào mừng {mention}! Chúc bạn luôn giữ được nụ cười rạng rỡ trên môi! 😁",
    "{mention} đã vào! Nơi đây luôn sẵn sàng chào đón bạn mọi lúc mọi nơi! 🏠",
    "{mention} vừa vào phòng! Đừng quên dùng /hdsd để khám phá các lệnh hay nhé! 📖",
    "Chào mừng {mention}! Một buổi tối tuyệt vời cùng những người bạn tuyệt vời! 🌌",
    "{mention} đã kết nối! Cùng nhau đàm đạo chuyện quốc gia đại sự nào! 🗺️",
    "{mention} vừa vào phòng thoại! Tiếng gọi của đồng đội đã đưa bạn về đây! 🎺",
    "Chào mừng {mention}! Hãy tự tin khoe cá tính qua từng câu nói nhé! 💃",
    "{mention} đã vào! Hãy cùng nhau xả hết những áp lực mệt mỏi trong ngày! 💆‍♂️",
    "{mention} vừa xuất hiện! Sự có mặt của bạn là niềm vinh hạnh của cả phòng! 💐",
    "Alo {mention}! Vào rồi thì mau lên mic, đừng để chị Google gọi tên! 🤖",
    "Chào mừng {mention}! Chúc bạn có những giây phút giải trí thăng hoa nhất! 🚀",
    "{mention} đã vào phòng thoại! Đêm nay chúng ta là những người bất tử! 🧛‍♂️",
    "{mention} vừa kết nối thành công! Cả phòng chính thức bắt đầu quậy phá! 💥",
    "Chào mừng đại ca {mention} đã ngự giá quang lâm vào phòng thoại! 👑🎉"
]

# 100 CÂU THÔNG BÁO RỜI PHÒNG VOICE (VC LEAVE)
VC_LEAVE_MESSAGES = [
    "{mention} lại sủi đi ỉa rồi à? 💩",
    "{mention} đã cúp đuôi chạy trốn. 🏃",
    "{mention} biến mất nhanh hơn crush rep tin nhắn mày. 💨",
    "Ơ {mention} đi đâu đấy, sợ bị đấm à? 🥊",
    "{mention} đã rời khỏi cuộc trò chuyện vì không chịu nổi áp lực. 🍂",
    "Vừa thấy mặt {mention} xong lại bay màu rồi! 🌫️",
    "{mention} đã bấm nút sủi trong sự khinh bỉ của anh em. 😒",
    "Tạm biệt {mention}, chắc là bị mẹ gõ đầu gọi đi ăn cơm rồi! 🍚",
    "{mention} đã ngắt kết nối! Đỡ ồn ào hẳn cái phòng! 🔇",
    "Ơ kìa {mention}, đang vui thì đứt dây đàn! 🎸💔",
    "{mention} đã tẩu thoát thành công khỏi hiện trường vụ án. 🚔",
    "Bay màu rồi! {mention} đã biến mất vào màn đêm u tối. 🌑",
    "{mention} đi ngủ sớm thế, đồ yếu sinh lý! 🛌💤",
    "Tạm biệt {mention}, hẹn kiếp sau lại vào voice nói chuyện tiếp nhé! 🪦",
    "{mention} đã rời phòng vì hết tiền 4G. 📶❌",
    "Ơ {mention}, chưa kịp chào anh em đã bấm nút té rồi! 🚪",
    "{mention} đã sủi bọt tăm! Cả phòng đồng thanh hô: ĐỒ HÈN! 🗣️",
    "Một bóng hình vừa vụt tắt... {mention} đã rời xa chúng ta. 🕯️",
    "{mention} đã out voice! Chắc là đi nhắn tin với crush rồi. 💌",
    "Tạm biệt {mention}, cảm ơn vì đã vào phòng thở vài hơi rồi đi! 😮‍💨",
    "{mention} đã rời khỏi phòng thoại để đi bảo vệ thế giới. 🦸‍♂️",
    "Ơ {mention}, sợ bị chị Google đọc trúng tim đen hay sao mà sủi? 🤖",
    "{mention} đã out! Phòng thoại bỗng trở nên yên bình đến lạ thường. 🍃",
    "Tạm biệt {mention}, người đi một nửa hồn tôi mừng! 🥳",
    "{mention} đã rút lui trong im lặng không một lời từ biệt. 🕊️",
    "Bay màu! {mention} đã không thể trụ lại trong môi trường khắc nghiệt này. 🌋",
    "{mention} đã out voice! Chắc là bị rớt mạng rồi. 🔌",
    "Tạm biệt {mention}, chúc bạn có một giấc ngủ đẫm nước mắt! 😭",
    "{mention} đã sủi! Mong bạn sớm tìm lại được dũng khí để quay lại. 🛡️",
    "Ơ {mention}, đi đâu vội thế con lợn? 🐷",
    "{mention} đã rời phòng thoại! Một ghế trống lại xuất hiện. 🪑",
    "Tạm biệt {mention}, người từng hứa ở lại thâu đêm nhưng sủi lúc 10h. ⏰",
    "{mention} đã biến mất như một bóng ma! 👻",
    "Bay màu rồi! {mention} không chịu nổi nhiệt đã bấm nút thoát hiểm. 🚨",
    "{mention} đã out voice để đi cày phim tình cảm. 🎬",
    "Tạm biệt {mention}, hẹn gặp lại bạn ở những trận thua tiếp theo! 📉",
    "{mention} đã rời khỏi cuộc họp khẩn cấp của chuồng hề. 🎪",
    "Ơ {mention}, chưa kịp hát xong một bài đã tắt mic bỏ đi! 🎤❌",
    "{mention} đã sủi! Cả phòng hụt hẫng một cách sâu sắc. 🕳️",
    "Tạm biệt {mention}, chúc bạn sang phòng khác không bị troll! 🤡",
    "{mention} đã out! Đi đâu thì đi nhớ quay lại đóng tiền nhé! 💸",
    "Một nén nhang tiễn đưa {mention} rời khỏi phòng thoại an lành. 🪔",
    "{mention} đã biến mất nhanh hơn cả lương về tài khoản. 💳💨",
    "Tạm biệt {mention}, chúc bạn sớm cai nghiện voice thành công! 💊",
    "{mention} đã out voice! Chắc là đi nấu cơm rửa bát cho vợ rồi. 🍳",
    "Ơ {mention}, trốn đi đâu đấy? Anh em đang tìm mày kìa! 🔍",
    "{mention} đã sủi! Một cuộc tẩu thoát ngoạn mục! 🧗‍♂️",
    "Tạm biệt {mention}, để lại bao tiếc nuối và một sự im lặng đáng sợ. 🤫",
    "{mention} đã rời phòng thoại vì bị đau họng. 🍵",
    "Bay màu! {mention} đã chính thức rời khỏi cuộc chơi. 🛑",
    "{mention} đã out! Hy vọng bạn không giận dỗi gì anh em trong này. ❤️",
    "Tạm biệt {mention}, người bạn từng hứa sẽ gánh team nhưng sủi trước. 🏋️❌",
    "{mention} đã ngắt kết nối! Tín hiệu đã bị mất hoàn toàn! 📡",
    "Ơ {mention}, đi vệ sinh nhớ rửa tay nhé con! 🧼",
    "{mention} đã sủi! Cả phòng bớt đi một cái loa rè. 📻",
    "Tạm biệt {mention}, chúc bạn có một đêm ngon giấc không mộng mị! 🌙",
    "{mention} đã rời khỏi phòng thoại trong sự tiếc thương vô hạn. 🥀",
    "Bay màu rồi! {mention} đã bị thế lực ngầm lôi kéo ra ngoài. 🕳️",
    "{mention} đã out voice để đi kiếm người yêu. 👩‍❤️‍👨 (chúc may mắn)",
    "Tạm biệt {mention}, hẹn ngày tái ngộ trên chiến trường Discord! ⚔️",
    "{mention} đã sủi như một cơn lốc xoáy! 🌪️",
    "Ơ {mention}, chưa kịp nói gì mà đã bấm nút té nhanh như chớp! ⚡",
    "{mention} đã rời phòng thoại! Đề nghị anh em không bàn tán sau lưng nó! 👥",
    "Tạm biệt {mention}, người hùng thầm lặng đã lui về ở ẩn. 🏔️",
    "{mention} đã out! Chắc là máy tính bị nổ nguồn rồi. 💥",
    "Bay màu! {mention} đã chọn cách từ bỏ cuộc trò chuyện này. 🚪",
    "{mention} đã sủi! Mong bạn luôn giữ vững niềm tin vào cuộc sống. 🌟",
    "Tạm biệt {mention}, kết thúc một buổi voice đầy sóng gió. 🌊",
    "{mention} đã rời khỏi phòng thoại vì bị gọi lên bảng! 📋",
    "Ơ {mention}, đi đâu đấy? Để quên não ở lại rồi kìa! 🧠",
    "{mention} đã out voice! Chúc bạn sớm tìm được chân lý cuộc đời. ☀️",
    "Tạm biệt {mention}, người bạn đồng hành từng cùng nhau thức trắng. ☕",
    "{mention} đã sủi! Đỡ phải nghe nó gáy nhức cả đầu! 🙉",
    "Bay màu rồi! {mention} đã tan biến vào không gian bao la. 🌌",
    "{mention} đã rời phòng thoại trong sự ngỡ ngàng của mọi người. 😲",
    "Tạm biệt {mention}, người ra đi để lại một khoảng trống to đùng. 🕳️",
    "{mention} đã out! Chắc là đi ăn mì tôm đêm rồi. 🍜",
    "Ơ {mention}, sủi sớm thế mai lấy sức đâu mà đi học? 🎒",
    "{mention} đã rời khỏi phòng thoại! Cuộc vui chính thức tàn một nửa! 🎈",
    "Tạm biệt {mention}, chúc bạn luôn bình an trên mọi nẻo đường! 🛣️",
    "{mention} đã sủi! Một pha rút lui cực kỳ bài bản và chuyên nghiệp. 🎖️",
    "Bay màu! {mention} đã không thể chống lại cơn buồn ngủ ngàn năm. 🥱",
    "{mention} đã out voice! Đừng quên quay lại khi rảnh rỗi nhé! 🔄",
    "Tạm biệt {mention}, người bạn từng cùng nhau chia sẻ bao niềm vui. 🤝",
    "{mention} đã rời phòng thoại vì hết pin tai nghe. 🔋❌",
    "Ơ {mention}, vừa mới vào được 5 phút đã bấm nút té rồi à? ⏱️",
    "{mention} đã sủi! Cả phòng đồng thanh hô: CHÀO THÂN ÁI VÀ QUYẾT THẮNG! 🫡",
    "Tạm biệt {mention}, chúc bạn sang server khác không bị bắt nạt! 🥺",
    "{mention} đã out! Hãy nghỉ ngơi thật tốt để mai lại vào cãi nhau tiếp nhé! 🛌",
    "Bay màu rồi! {mention} đã rời bến đỗ an toàn để ra khơi. ⛵",
    "{mention} đã sủi như một vị thần bóng tối! 🕶️",
    "Tạm biệt {mention}, để lại bao kỷ niệm đẹp đẽ trong phòng voice này. 📸",
    "{mention} đã rời khỏi cuộc trò chuyện! Một phút im lặng bắt đầu! ⏳",
    "Ơ {mention}, đi đâu đấy? Còn đống bài tập về nhà chưa làm kìa! 📚",
    "{mention} đã out voice! Chúc bạn có những giấc mơ thật đẹp! 🌈",
    "Tạm biệt {mention}, người bạn dũng cảm đã hoàn thành ca trực đêm! 🌙",
    "{mention} đã sủi! Hãy nhớ rằng phòng thoại này luôn mở cửa đón bạn! 🚪",
    "Bay màu! {mention} đã chính thức rời khỏi tầm mắt của mọi người! 🔭",
    "{mention} đã out! Hẹn gặp lại bạn vào một ngày đẹp trời gần nhất! ☀️",
    "Chính thức tiễn đưa {mention} rời khỏi phòng thoại! Chúc may mắn! 💨👋"
]
